### ISSUE TITLE
document regional/endpoint

### ISSUE THREAD

**Issue by johnabela** [daniel-zahariev/php-aws-ses#10]
Hello,

It would be nice to have the documentation include how to access the different regional/endpoints.

http://docs.aws.amazon.com/general/latest/gr/rande.html#ses_region

$ses = new SimpleEmailService(AccessKey, SecretKey,'email.us-west-2.amazonaws.com'); // US West (Oregon) HTTPS

It appears to default to the 'email.us-east-1.amazonaws.com' US East (N. Virginia) HTTPS

**Comment by xiangwenquan** [comment]
indeed!

**Comment by hubdotcom** [comment]
+1

The list of regions is here for reference: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/regions.html

**Comment by daniel-zahariev** [comment]
Thanks for the suggestion! A few class constants in SimpleEmailService are now preset and available for  selecting a region.
