### ISSUE TITLE
reply-to address is ignored when sending attachments

### ISSUE THREAD

**Issue by mikeatxcstats** [daniel-zahariev/php-aws-ses#17]
If you add an attachment, any assignment for the reply-to address is ignored and a reply is addressed to the sending address.  For the same code without an attachment, a reply is correctly addressed to the reply-to address.

**Comment by mikeatxcstats** [comment]
I am not an OO programmer but I added this line:

$raw_message .= 'Reply-to: ' . $this->encodeRecipients($this->replyto) . "\n";

 on line 230 of SimpleEmailServiceMessage.php and it works!

**Comment by daniel-zahariev** [comment]
Thanks, this is now fixed.
