### ISSUE TITLE
Doesn't send e-mail

### ISSUE THREAD

**Issue by mn1aC** [daniel-zahariev/php-aws-ses#18]
Hi,

I have created a new users via IAM, and added the AmazonSESFullAccess policy.
$ses = new SimpleEmailService('ACCESSKEY', 'VALUE');
print_r($ses->verifyEmailAddress('my_email@mail.com'));
nothing is printed?

What am I doing wrong. (libraries are loaded successfully)

**Comment by daniel-zahariev** [comment]
Hi Sven,
the purpose of this method is to add the given mail to the white listed ones used in the 'From:' field.
What it does is that it sends verification email to the specified email address with link to activate it.
Check the docs here: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-email-addresses.html
