### ISSUE TITLE
How can we set the sender and recipient name ?

### ISSUE THREAD

**Issue by devkiran** [daniel-zahariev/php-aws-ses#23]
is there any functions in the existing library to set sender and recipient name ?

**Comment by daniel-zahariev** [comment]
As in the docs you can use `$m->addTo('Jim Carrey <jim@example.com>');` to set the recipient's name and it's the same with sender: `$m->setFrom('Jim Carrey <jim@example.com>');`

**Comment by devkiran** [comment]
I tried with that, but it gives the following errors

Message: SimpleEmailService::sendEmail(): Sender - MessageRejected: Email address is not verified. And without the recipient's name it works fine.

**Comment by daniel-zahariev** [comment]
Do you mean that without sender's name it works and with it - it doesn't?
Have you actually verified the email you're sending emails from? 
There's a method that would trigger the verification process and email will be sent with verification link.

**Comment by devkiran** [comment]
@daniel-zahariev Sorry that was my mistake. It worked perfectly. Thanks :+1:
