### ISSUE TITLE
there are some "echo" in code not removed

### ISSUE THREAD

**Issue by mingdongcui** [daniel-zahariev/php-aws-ses#27]
when I am executing the code, say, send a email, there are some header and response array information "echo"ed out onto the html, I traced it to be inside the SimpleEmailServiceRequest.php code, obviously for debugging purpose. there is one "echo" in SimpleEmailService.php also.

can that be removed?

**Comment by daniel-zahariev** [comment]
Hi @mingdongcui, the `echo` is commented in `SimpleEmailService.php` and from what i understand it's the main issue. Can you provide me a code example so that i can try and reproduce the issue.
Thanks

**Comment by mingdongcui** [comment]
Daniel,

    My problem comes from the "echo" lines in SimpleEmailServiceRequest.php, if I embedded some php code in my .html to send a mail, for example 
<?php $ses->sendEmail(...);?>
it will output some header and var_dump plain text information which will be mixed with my other html elements and be displayed in that webpage. my solution is to simply modify SimpleEmailServiceRequest.php and commented out those "echo" lines, since looks to me they are only for feedback and debugging purpose, and does not impact the mail fuction? or maybe I did not uses your code correctly? you may advise.

    And many many thanks for your awesome code, other than that small issue, it works very well on my website.

**Comment by daniel-zahariev** [comment]
Hi @mingdongcui,
there is only one `echo` line in the code which is [already commented](https://github.com/daniel-zahariev/php-aws-ses/search?utf8=%E2%9C%93&q=echo).
Can you check if you have done any modifications? What is the level of error reporting that you use and is it causing this mixup? There can be many more cases for this to happen and if i'm not able to reproduce it - i can't really help.

**Comment by mingdongcui** [comment]
Daniel

    thanks very much for your help, I just found that I am using an old version of the code you wrote, and there some some "echo" here and there, your latest code does have them any more, I should make an copy over. sorry for the confusion.

    Best wishes.
