### ISSUE TITLE
Arabic emails

### ISSUE THREAD

**Issue by goldendousa** [daniel-zahariev/php-aws-ses#28]
I couldnt find a way to send an email which contain arabic characters ?

**Comment by daniel-zahariev** [comment]
Hi,
there is a requirement for the recipients list to be [7-bit ASCII](http://docs.aws.amazon.com/ses/latest/APIReference/API_Destination.html). Here is [the line](https://github.com/daniel-zahariev/php-aws-ses/blob/master/src/SimpleEmailServiceMessage.php#L319) where you can play around and try to make it work. My tests with non-ASCII characters resulted with errors and couldn't get around it.

Regards,
Daniel
