### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by Mark-H** [daniel-zahariev/php-aws-ses#29]
Not a bug report or anything, but....

Nice work. This library saved me a ton of work trying to get the SES api to send my attachments. 

Do you have PayPal or another way to send you some 🍻 or ☕ or whatever else you prefer?

**Comment by daniel-zahariev** [comment]
Hi @Mark-H,
thanks for the kudos! I feel hesitant to take any donations as most of the codebase was done by Dan Myers who is mentioned in the description of the project. If you insist - my PayPal is daniel.zahariev@gmail.com.

Regards,
Daniel

**Comment by Mark-H** [comment]
🍻 / ☕ has been sent :) I see your work on these classes was implementing the raw mail stuff, which is exactly what I needed. Thanks for sharing your work.

**Comment by daniel-zahariev** [comment]
Thanks @Mark-H, got the 🍻 and really appreciate it!
