### ISSUE TITLE
improve with persistent connection

### ISSUE THREAD

**Issue by damanic** [daniel-zahariev/php-aws-ses#30]
Thanks for the code, I'm using this to send email out in loops of 10,000 and found that throughput can be more than doubled if you allow CURL to persist between requests.

Here is an example loop that could be made much quicker if the curl connection persisted.

```
$ses = new MjmList\SimpleEmailService(trim($config->amazonses_access_key), trim($config->amazonses_secret_key));
$html_content = $newsletter->fetch_content_html();

while($count < 10000){
            $recipient = array(
                'name' => 'test',
                'email' => 'success@simulator.amazonses.com',
            );
            $m = new MjmList\SimpleEmailServiceMessage();
            $to = empty($recipient['name']) ? $recipient['email'] : $recipient['name'].'<'.$recipient['email'].'>';
            $from = $newsletter->profile->senders_name.'<'.$newsletter->profile->reply_to_email.'>';
            $msg_content = $newsletter->apply_content_vars($recipient,$html_content);

            $m->addTo($to);
            $m->setFrom($from);
            $m->setSubject($newsletter->title);
            $m->setMessageFromString($msg_content, true);
           $ses->sendEmail($m);
            $count++;
            echo 'sent '.$count.'<br/>';
        }
```

If curl_init() is done once by `SimpleEmailService` and its handle passed on to all requests called through that service, curl will be able to keep sending out requests on the same https connection without the painful overhead of reconnects for each request.

**Comment by daniel-zahariev** [comment]
Hi @damanic, thanks for the feedback. Will look into this shortly.

**Comment by christianseel** [comment]
That would indeed be a nice feature. I've got the same use case…
