### ISSUE TITLE
Install without composer

### ISSUE THREAD

**Issue by bersujamu** [daniel-zahariev/php-aws-ses#33]
Hi, composer is very good. But, is it possible to do manual installation?

**Comment by mkwsra** [comment]
You can just download the files within the `src` folder and use it 
[https://github.com/daniel-zahariev/php-aws-ses/tree/master/src](Src Folder)

**Comment by daniel-zahariev** [comment]
hi @bersujamu, 
as @mkwsra said you can download the files in the `src` folder, require them manually and use them in your project.
