### ISSUE TITLE
It emits an error if PHP can not find the security certificate on Windows

### ISSUE THREAD

**Issue by mehmetcnet** [daniel-zahariev/php-aws-ses#34]
It emits an error if PHP can not find the security certificate on Windows.

Solution is:

```
$cert = dirname(__FILE__) . '/data/ca-certificates.crt';
curl_setopt($curl, CURLOPT_CAINFO, $cert);
```

I think this problem occurs on only Windows systems since UNİX/Linux PHP installs are able to automatically find security certificates.

**Comment by daniel-zahariev** [comment]
Hi @mehmetcnet,
yes, this seems to be a specific issue.
I'd advise you to solve it as follows:
```
$cert = dirname(__FILE__) . '/data/ca-certificates.crt';
SimpleEmailServiceRequest::$curlOptions[CURLOPT_CAINFO] = $cert;
```
