### ISSUE TITLE
Sending Speed

### ISSUE THREAD

**Issue by rogercrandall** [daniel-zahariev/php-aws-ses#37]
Here is my current setup, and I am only able to send 2-3 emails a second. How can I speed this up?

In the same setup, I am able to send 100+ per second on sendgrid, so I know its no the database query that is slowing me down. Thank you in advance for any help. I am relatively new to using github, so I apologize if this is the wrong place to ask this. Also, my SES account allows for up to 120 calls per second.
```

$ses = new SimpleEmailService(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY);
$ses->setBulkMode(true);

while(){ // i run through a database
		
	$m = new SimpleEmailServiceMessage();
	$m->addTo( $email );
	$m->setFrom( $from_name.' <'.$from_email.'>' );
	$m->setSubject( $subject );
	$m->setMessageFromString( $textBody,$body );
	$m->addCustomHeader('List-Unsubscribe: <'.$unsubEmail.'>, <'.$unsubLink.'>');

	try {
		$ses->sendEmail($m,$use_raw_request = true);
	} catch (Exception $e) {
		echo $e;
	}

}

$ses->setBulkMode(false);
```

**Comment by daniel-zahariev** [comment]
Hi @rogercrandall, i'll run some tests tonight and will get back to you tomorrow.

**Comment by tribulant** [comment]
I'm having the same problem here, the sending is very slow.

The setBulkMode() method is reusing the connection to make it persistent it seems so that already speeds it up but for some reason it still remains very slow.

I'm digging here and if I find anything will reply back but any input will be helpful. I'll be using the Amazon SES mailbox simulator here to see how I can increase performance.

**Comment by daniel-zahariev** [comment]
Still haven't figured this out yet...
I also get the same speed and haven't found a way to increase the performance yet 😞

**Comment by tribulant** [comment]
I managed to get some speed improvements by speeding up PHP curl.

`curl_setopt($ch, CURLOPT_ENCODING,  '')`
`curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 );`

Does increase the speed a bit as well as turning off verify host and peer but that is not recommended.

Deeper than that I haven't dug yet. I'll test out the actual Amazon AWS SDK to see how they make a connection and then I can possibly suggest something?

**Comment by daniel-zahariev** [comment]
Hey @tribulant, did you manage to run tests with Amazon AWS SDK?

**Comment by tribulant** [comment]
@daniel-zahariev 

Yes, we did extensive testing with the Amazon SES sandbox and altered some code but there is no real way of increasing the sending speed. It just takes time to make a connection and communicate with Amazon SES, that's just how it is.

They have a guide here on ways to increase throughput: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/throughput-problems.html . They also mention at the top of that article that it does take time to send an email.

We are currently working on a multi-threading PHP simulation to run multiple tasks to send emails using this Amazon SES class for PHP and that should be the ultimate solution.
