### ISSUE TITLE
Erroneous Message Failed Validation

### ISSUE THREAD

**Issue by championchap** [daniel-zahariev/php-aws-ses#38]
Hey there,

Thanks for putting this library together, it's been very helpful! However I think I have run into a problem with it. 

When sending a HTML formatted email an `ErrorException` gets thrown with the message `Message failed validation.`. If I run `validate()` on the message right before I send it, validate returns `true`. Also, the message does get sent and I receive the HTML formatted message just fine. 

Here's the code that I've been using. We're running `PHP 7.0.13` on the dev server at the moment. 

Seems really odd to me at first glance, as the SimpleEmailService object looks like it's just calling validate on the message too? I dunno, maybe I'm just misusing it somehow. 

```php
// $message is just an array of the from, to, subject, etc
// $ses is the SimpleEmailService instance
private function sendMessage ($message, $ses) {
    $mail = new SimpleEmailServiceMessage();

    $mail->addTo($message['to']);
    $mail->setFrom($message['from']);
    $mail->setSubject($message['subject']);

    $mail->setMessageFromString(
        strip_tags($message['message']),
        $message['message']
    );

    if(isset($message['attach'])) {
        $mail->addAttachmentFromFile(
            $message['file_name'],
            $message['file_path'],
            $message['mime_type']
        );
    }

    var_dump($mail->validate()); // returns true 
    $ses->sendEmail($mail); // Throws a "Message failed validation." 
}
```

**Comment by daniel-zahariev** [comment]
This is very odd indeed.

**Comment by daniel-zahariev** [comment]
Hey @championchap, did you find what was wrong with this?

**Comment by championchap** [comment]
@daniel-zahariev no I didn't. In the end I just ignored the error messages and kept my fingers crossed. It is coping well with a couple thousand emails / day at the moment though. 

Really very strange.
