### ISSUE TITLE
Send mail without 'to'

### ISSUE THREAD

**Issue by johnswyen** [daniel-zahariev/php-aws-ses#41]
how can i send an email to only 'cc' or 'bcc' recipient instead of 'to'
i've got the error [Sender - InvalidParameterValue: Empty required header 'To'.]

**Comment by daniel-zahariev** [comment]
Hey @johnswyen, i've merged a pull request yesterday that allows empty 'To' recipients list.
And now i've increased the version so that this is reflected in packagist.com

**Comment by johnswyen** [comment]
@daniel-zahariev, many thanks. we've confirmed the latest version can send empty 'To' successfully.
