### ISSUE TITLE
Can we add support for SendRawEmailAsync?

### ISSUE THREAD

**Issue by CBox** [daniel-zahariev/php-aws-ses#43]
Hey,

I'm trying to add another action for sending an email:
sendRawEmailAsync

But I'm getting an error:
Sender - InvalidAction: Could not find operation SendRawEmailAsync for version 2010-12-01

I don't think there is newer version than this but there is an option to send SendRawEmailAsync:
http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-email-2010-12-01.html#sendrawemail

If you can point me to the right direction I'll make the changes and commit :)

Thanks.

**Comment by daniel-zahariev** [comment]
Hi @CBox, the documentation you're referring to is for Amazon's PHP SDK. 
The current package doesn't provide the method `sendRawEmailAsync`.
