### ISSUE TITLE
IMPORT IN LUMEN

### ISSUE THREAD

**Issue by lanzosuarez** [daniel-zahariev/php-aws-ses#46]
How do i import SimpleEmailServiceMessage in Lumen.

**Comment by daniel-zahariev** [comment]
After the installation of the package via Composer: 
`composer require daniel-zahariev/php-aws-ses` 
you have to either add it to the `use` block of the file like this: 
`use SimpleEmailServiceMessage;` 
or create instances with the full name (e.g. namespaces included) of the class which in this case should look like this: 
`$message = new \SimpleEmailServiceMessage();`

Hope this solves it for you.

**Comment by lanzosuarez** [comment]
It didnt work :(

**Comment by daniel-zahariev** [comment]
This shouldn't happen in the presence of backslash before the class name.
Read through namespaces usage again: http://php.net/manual/en/language.namespaces.basics.php

**Comment by lanzosuarez** [comment]
maybe because this statement 'namespace App\Http\Controllers' is on the top of my php controller file? what do you think?

**Comment by lanzosuarez** [comment]
Its working now. Thank.  :)
