### ISSUE TITLE
ConfigurationSet not working

### ISSUE THREAD

**Issue by mangeshn** [daniel-zahariev/php-aws-ses#53]
Hello,

We are using piece of code you shared here, and emails is shooting perfectly fine. But when we passing configuration set with sendEmail method, it not picking up configuration set. Because received email not having headers for configset as well as sender ip is shared instead of our dedicated pool which we assigned to one of our config set.

Hope you will help on same. Thanks in Advance.

**Comment by daniel-zahariev** [comment]
hi @mangeshn, ConfigurationSets are zone specific - so if you have multiple zones you should setup the config in each one of them. Can you confirm that this isn't the issue?

**Comment by mangeshn** [comment]
Hello Daniel,

I am using ireland region and config i made is in same region. Emails are shooting from perfect region but just issue is it's not picking up my config for dedicated pool.

**Comment by mangeshn** [comment]
Hello Daniel,

Sorry! it's working fine :) i was missing configuration set check in sendEMail.

Good Stuff 👍

**Comment by daniel-zahariev** [comment]
thanks!
