### ISSUE TITLE
Getting bounce addresses

### ISSUE THREAD

**Issue by tima86** [daniel-zahariev/php-aws-ses#54]
Hi, method getSendStatistics() returns quantity bounces. How to get bounces email addresses?
Thanks!

**Comment by daniel-zahariev** [comment]
Hi @tima86,
are you asking about this method: https://docs.aws.amazon.com/ses/latest/APIReference/API_SendBounce.html

**Comment by tima1605** [comment]
I need to get emails with bounces. Only email addresses, letter text is not needed. How can I do it with api.
Sorry for my English.
