### ISSUE TITLE
can not send email 

### ISSUE THREAD

**Issue by UMDEVELOPER** [daniel-zahariev/php-aws-ses#55]
I have problem in this code write properly but can not send email show no any error.
 ```
    $this->load->library('Aws_ses_new/SimpleEmailService'); 
    $this->load->library('Aws_ses_new/SimpleEmailServiceMessage');  
    $this->load->library('Aws_ses_new/SimpleEmailServiceRequest');  
    $ses = new SimpleEmailService('xxxxxxxxx', 'xxxxxxxxx');
    $m = new SimpleEmailServiceMessage();
    $m->addTo('abc@gmail.com');
    $m->setFrom('abc@gmail.com');
    $m->setSubject('Hello, world!');
    $m->setMessageFromString('This is the message body.');
    print_r($ses->sendEmail($m));
```

**Comment by daniel-zahariev** [comment]
Hi, did you make sure to verify the email sender? 
If yes - did you check if you got any [errors](https://github.com/daniel-zahariev/php-aws-ses#errors)

**Comment by UMDEVELOPER** [comment]
ok i have done it

**Comment by UMDEVELOPER** [comment]
and thanks
I want to make login panel for amazon SE for user so i want to credentials with SES so can you help me that case form example show in image 
![screenshot_1](https://user-images.githubusercontent.com/5516828/39993914-0556c80e-5791-11e8-9972-ce5331cedae6.jpg)

**Comment by daniel-zahariev** [comment]
Hi @UMDEVELOPER, i'm sorry but this is out of the scope of the project.
