### ISSUE TITLE
addAttachmentFromFile not working in CLI mode

### ISSUE THREAD

**Issue by aa6my** [daniel-zahariev/php-aws-ses#73]
hello, sorry for take your time. Attachment not working using CLI, array are empty. It will send an email without attachment.

![image](https://user-images.githubusercontent.com/7272163/91295113-27302500-e7cd-11ea-81bc-35e02bfa8176.png)
![image](https://user-images.githubusercontent.com/7272163/91294943-e0dac600-e7cc-11ea-81ab-af6c4e7139cb.png)
![image](https://user-images.githubusercontent.com/7272163/91294781-a2450b80-e7cc-11ea-9dfb-dc16987474d6.png)

**Comment by daniel-zahariev** [comment]
Hi @aa6my, is the value of `$file->path` the actual real path with the filename included?

**Comment by aa6my** [comment]
> Hi @aa6my, is the value of `$file->path` the actual real path with the filename included?

yup, here the censored string for $file->path  `C:\Users\xxxxxx\Code\xxxxx_xxxxxx`

**Comment by daniel-zahariev** [comment]
Can you check if `addAttachmentFromFile` returns false?

**Comment by aa6my** [comment]
yes it is, after i dd `dd($m->addAttachmentFromFile$file->name, $file->path, $file->type));` its show `false`

**Comment by aa6my** [comment]
@daniel-zahariev here my extra information

Authentication
```
$region = SimpleEmailService::AWS_US_EAST_1;
$version = SimpleEmailService::REQUEST_SIGNATURE_V4;
$debug = true;

$ses = new SimpleEmailService(
    $_ENV['AWS_ACCESS_KEY_ID'], 
    $_ENV['AWS_SECRET_ACCESS_KEY'], 
    $region,
    $debug,
    $version
);
$ses->setHost($_ENV['SES_REGION']);
```

ENV
```
AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
AWS_DEFAULT_REGION=ap-southeast-1
SES_REGION=email.ap-southeast-1.amazonaws.com
```

**Comment by aa6my** [comment]
Okay, it works with another method, here the example

index.php
```php
<?php

require_once 'vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$recipientName = $_ENV['RECIPIENT_NAME'];
$recipientEmail = $_ENV['RECIPIENT_EMAIL'];

$senderName = $_ENV['SENDER_NAME'];
$senderEmail = $_ENV['SENDER_EMAIL'];

$file = 'https://test.test.asia/test/file_2020-08-26-15-11-32.csv';
$type = wapmorgan\FileTypeDetector\Detector::detectByFilename($file)[2];

$m = new SimpleEmailServiceMessage();
$m->addTo("$recipientName <$recipientEmail>");
$m->setFrom("$senderName <$senderEmail>");
$m->setSubject('Hello, world!');
$m->setMessageFromString('This is the message body.');
$m->addAttachmentFromUrl(basename($file), $file, $type);

$region = SimpleEmailService::AWS_US_EAST_1;
$version = SimpleEmailService::REQUEST_SIGNATURE_V4;
$debug = true;

$ses = new SimpleEmailService(
    $_ENV['AWS_ACCESS_KEY_ID'], 
    $_ENV['AWS_SECRET_ACCESS_KEY'], 
    $region,
    $debug,
    $version
);
$ses->setHost($_ENV['SES_REGION']);

// dd($m);

try {
    $ses->sendEmail($m,$use_raw_request = true);
} catch (Exception $e) {
    echo $e;
}
```

.env
```
AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
AWS_DEFAULT_REGION=ap-southeast-1
SES_REGION=email.ap-southeast-1.amazonaws.com

RECIPIENT_NAME="Mark R"
RECIPIENT_EMAIL=your@recipient.com

SENDER_NAME="Johnny S"
SENDER_EMAIL=your@sender.com

FILENAME=test.txt
```

composer.json
```json
{
    "name": "aa6my/php-aws-ses-cli",
    "description": "php-aws-ses in CLI",
    "require": {
        "daniel-zahariev/php-aws-ses": "^0.9.2",
        "vlucas/phpdotenv": "^5.1",
        "wapmorgan/file-type-detector": "^1.1",
        "wanfeiyy/dd": "^1.0"
    }
}
```

test.txt
```txt
test
```

**Comment by TomS-** [comment]
Thanks for this, I was running into the same problem and I couldn't figure out why. Using addAttachmentFromUrl worked. Glad I searched closed issues.

**Comment by snzmnrdn** [comment]
> Thanks for this, I was running into the same problem and I couldn't figure out why. Using addAttachmentFromUrl worked. Glad I searched closed issues.
> 
> EDIT:
> How come addAttachmentFromUrl isn't documented?

Btw, its not documented. So I just check it available & test it working. 
REF `SimpleEmailServiceMessage.php` - https://github.com/daniel-zahariev/php-aws-ses/blob/master/src/SimpleEmailServiceMessage.php#L467
