### ISSUE TITLE
Header errors when sending attachments

### ISSUE THREAD

**Issue by eddycoder** [daniel-zahariev/php-aws-ses#8]
If you're sending attachments, if you don't set at least one header using addCustomHeader() then you'll get errors such as "Warning: SimpleEmailService::sendEmail(): Sender - InvalidParameterValue: Missing required header 'From'."

**Comment by ststoyanov89** [comment]
Hi Daniel,

I experienced the same issue. The reason was that I don't have custom headers, and therefore getRawMessage is adding an extra new line which brokes everything. Just implement a check if count($this->customHeaders) > 0, an then join them.

Regards,
Stanimir

**Comment by ststoyanov89** [comment]
Hi Daniel,

Pull request 11 fixes this issue.

Regards,
Stanimir

**Comment by daniel-zahariev** [comment]
This is fixed now.
