### ISSUE TITLE
php 8 - getting some warnings

### ISSUE THREAD

**Issue by morrow95** [daniel-zahariev/php-aws-ses#81]
Just started using php 8 and notice some warnings showing up in the logs.  Functionality is there, but just wanted to make you aware of these so any changes for php 8 can be made as needed.

SimpleEmailServiceRequest.php line 172 on v0.9.2

```
		// Execute, grab errors
		if (curl_exec($curl_handler)) {
			$this->response->code = curl_getinfo($curl_handler, CURLINFO_HTTP_CODE);
		} else {
			$this->response->error = array(
				'curl' => true,
				'code' => curl_errno($curl_handler),
				'message' => curl_error($curl_handler),
			);
		}
```

throws : 

`
PHP Warning:  SimpleEmailServiceRequest::__responseWriteCallback(): Argument #1 ($curl) must be passed by reference, value given in`
`PHP Warning:  SimpleEmailServiceRequest::__responseWriteCallback(): Argument #2 ($data) must be passed by reference, value given in
`

**Comment by mertafor** [comment]
+1 on this. Mail is being sent but curl_exec throws a warning.

**Comment by webprogrammierer** [comment]
Same Problem here:

Warning: SimpleEmailServiceRequest::__responseWriteCallback(): Argument #1 ($curl) must be passed by reference, value given in ../aws-ses/vendor/daniel-zahariev/php-aws-ses/src/SimpleEmailServiceRequest.php on line 173

Warning: SimpleEmailServiceRequest::__responseWriteCallback(): Argument #2 ($data) must be passed by reference, value given in ../aws-ses/vendor/daniel-zahariev/php-aws-ses/src/SimpleEmailServiceRequest.php on line 173


Solution could be:
```
//private function __responseWriteCallback(&$curl, &$data) {
private function __responseWriteCallback($curl, $data) {  
```

in SimpleEmailServiceRequest.php.
