### ISSUE TITLE
SendRaw 

### ISSUE THREAD

**Issue by dwertheimer** [daniel-zahariev/php-aws-ses#9]
Thank you for adding RawEmail capability. That came in very handy to me.

One minor bug: in SimpleEmailService::sendEmail, Line 351

It sends back the messageID and the requestID. It appears that AWS/SES returns a different XML format when you send a RAW request, so you should update Line 351 to point to the proper place depending on whether ($action == 'SendRawEmail')

![jfdp](https://cloud.githubusercontent.com/assets/8949588/4482351/c6f8ddcc-49a7-11e4-8d2e-582e3536c6dc.jpg)

**Comment by daniel-zahariev** [comment]
Long due but now fixed! Thanks.
